# Notation and terminology {.unnumbered}

| Notation            | Meaning                                        |
|---------------------|------------------------------------------------|
| $\boldsymbol{y}$                          | Response variable vector               |
| $\boldsymbol{u}$                        | Parameter vector of blocking effects      |
| $\hat{\boldsymbol{u}}_{llm}$            | Estimated parameter vector of blocking effects by log-likelihood maximization|
| $\boldsymbol{\tau}$                         | Parameter vector of treatments effects       |
| $\hat{\boldsymbol{\tau}}_{gls}$     | Estimated parameter vector of treatments effects by generalized least squares|
| $\hat{\boldsymbol{\tau}}_{llm}$     | Estimated parameter vector of treatments effects by log-likelihood maximization|
| $\boldsymbol{\epsilon}$     | Parameter vector of model error            |
| $\boldsymbol{Z}$                | Blocking factor matrix                         |
| $\boldsymbol{X}$            | Design matrix for treatments                   |
| $\boldsymbol{G}$            | Variance matrix for random effect              |
| $\boldsymbol{R}$            | variance matrix for model error                |
| $\mathcal{A}$               | The A-value                                    |
| $\boldsymbol{\Lambda}$        | Variance-covariance of estimated treatments effects|
| $\boldsymbol{D}$            | Transformation matrix of treatments|
| $\mathcal{D}$         | Design results                                  |
| $\mathcal{D}_{r,c}$     |The treatment at row $r$ and column $c$         |
| $\mathcal{U}$         | Adjacency matrix                                |
| $n_r$                 | Total number of rows |
| $n_c$                 | Total number of columns |
| $n_{\tau}$            | Total kinds of treatments|
| $C_{NB}$                      | Neighbour balance criteria |
| $MRS(\mathcal{D})$    | The minimum row span of design $\mathcal{D}$|
| $MCS(\mathcal{D})$    | The minimum column  span of design $\mathcal{D}$|
| $\boldsymbol{G}_{diag}$ | Diagonal $\boldsymbol{G}$ matrix|
| $\boldsymbol{R}_{diag}$ | Diagonal $\boldsymbol{R}$ matrix|
| $\boldsymbol{I}_n$ |  Identity matrix with size $n\times n$|
| $\sigma_{G_c}$ | Scaling constant for column effects|
| $\sigma_{G_r}$ | Scaling constant for row effects|
| $\sigma_{R}$ | Scaling constant for model error|
| $A(\boldsymbol{X})$ | A-value function maps design matrix $\boldsymbol{X}$ to its A-value|
| $\boldsymbol{X}_{new}$ | New design matrix generated by permutation|
| $\mathcal{D}_{new}$ | Design results corresponding to $\boldsymbol{X}_{new}$|
| $\boldsymbol{P}_{ij}$ | An identity matrix with $i$-th row and $j$-th row swapped|
| $C_{NB}$           | Neighbour balance criteria of $\mathcal{D}_{new}$ |
| $MRS(\mathcal{D}_{new})$ | The minimum row span of design $\mathcal{D}_{new}$|
| $MCS(\mathcal{D}_{new})$ | The minimum column  span of design $\mathcal{D}_{new}$|
| $T_{NB}$ | Tolerance for Neighbour balance criteria
| $T_{ED}$ | Tolerance for minimum row span and minimum column span|
| $s$ | Step length for random search|
| $t_{NB}$| Tolerance for Neighbour balance criteria for pairwise permutation|
| $t_{ED}$| Tolerance for minimum row span and minimum column span for pairwise permutation|
| $M$ | Maximum iteration number |
| $\{\boldsymbol{X}\}$ | Finite design searching space |
| $\{\boldsymbol{X}^*\}$ | A set of design matrix having optimal A-value|
| $T(t)$ | Temperature at $t$-th iteration|
| $\boldsymbol{X}_0$ | Initial design matrix|
| $n_p$  | Number of permutations  | 
| $\boldsymbol{G}_s$ | Variance matrix for random effect of simulation |
| $\boldsymbol{R}_s$ | variance matrix for model error of simulation    |
| $A_{blocksdesign}$ | A-value calculated by design function in blocksdesign package|
| $T_A$ | Tolerance for A-value in simulation|
| $A_{\bigtriangleup}$ | Difference of A-values between two design matrix|
| $A_{op}$ | A-value calculated by design function in blocksdesign package in example case|
| $A_{rs}$ | A-value result given by random search|
| $\mathcal{D}_{rs}$         | Design result of random search                               |
| $C_{SAlog}$ | Neighbour balance criteria of random search |
| $MRS(\mathcal{D}_rs)$ | The minimum row span of design $\mathcal{D}_rs$|
| $MCS(\mathcal{D}_rs)$ | The minimum column  span of design $\mathcal{D}_rs$|
| $A_{SAlog}$ | A-value result given by SA with log cooling schedule |
| $\mathcal{D}_{SAlog}$   |      Design result of SA with log cooling schedule  |
| $C_{SAlog}$ |  Neighbour balance criteria of SA with log cooling schedule |
| $MRS(\mathcal{D}_{SAlog})$ | The minimum row span of design $\mathcal{D}_{SAlog}$|
| $MCS(\mathcal{D}_{SAlog})$ | The minimum column  span of design $\mathcal{D}_{SAlog}$|
| $A_{SAexp}$ | A-value result given by SA with exp cooling schedule |
| $\mathcal{D}_{SAexp}$   |      Design result of SA with exp cooling schedule  |
| $C_{SAexp}$ |  Neighbour balance criteria of SA with exp cooling schedule |
| $MRS(\mathcal{D}_{SAexp})$ | The minimum row span of design $\mathcal{D}_{SAexp}$|
| $MCS(\mathcal{D}_{SAexp})$ | The minimum column  span of design $\mathcal{D}_{SAexp}$|
| $\mathcal{T}$ | Tabu list |




| Terminology | Meaning  |
|--------------|--------------|
| Evenness of distribution (ED) |  Multiple replications of a treatment are evenly spread across the design field |
| Neighbour balance (NB) | Multiple treatments are not consistently placed next to each other in the design |
| Pairwise permutation  |  Swapping two treatments in a design matrix to explore new configurations |